[general]
import = ["./catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[window]
decorations = "none"
opacity = 0.8
option_as_alt = "OnlyLeft"
padding = { x = 10, y = 10 }
blur = true

[font]
size = 22
normal = { family = "Iosevka Nerd Font Mono", style = "Regular" }
bold = { family = "Iosevka Nerd Font Mono", style = "Bold" }
bold_italic = { family = "Iosevka Nerd Font Mono", style = "Bold Italic" }
italic = { family = "Iosevka Nerd Font Mono", style = "Italic" }

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  { key = "C", mods = "Alt", action = "Copy" },
  { key = "V", mods = "Alt", action = "Paste" },
  { key = "Up", mods = "Control|Shift", action = "ScrollLineUp" },
  { key = "Down", mods = "Control|Shift", action = "ScrollLineDown" },
  { key = "PageUp", action = "ScrollHalfPageUp" },
  { key = "PageDown", action = "ScrollHalfPageDown" },
  { key = "Home", action = "ScrollPageUp" },
  { key = "End", action = "ScrollPageDown" },
  { key = "V", mods = "Control|Shift", action = "ToggleViMode" },
]
